# Netlify Configuration for TGE Monitor Frontend

[build]
  # Build settings
  base = "."
  command = "npm run build"
  publish = "dist"

# Redirect all routes to index.html for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Build environment
[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "10"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"

# Cache static assets for 1 year
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Don't cache index.html
[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

# Don't cache service worker (if you add one later)
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

# Enable HTTP/2 Server Push for critical assets
[[headers]]
  for = "/"
  [headers.values]
    Link = "</assets/index.css>; rel=preload; as=style, </assets/index.js>; rel=preload; as=script"
