# Nixpacks configuration for Railway deployment

[phases.setup]
nixPkgs = ["python311", "postgresql", "openssl"]
aptPkgs = ["libpq-dev", "build-essential"]

[phases.install]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt"]

[phases.build]
cmds = ["python --version"]

[start]
cmd = "uvicorn src.api:app --host 0.0.0.0 --port $PORT --workers 2"
