# Grafana Data Source Provisioning for TGE Swarm
# Configure Prometheus and other data sources

apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    jsonData:
      timeInterval: 15s
      queryTimeout: 60s
      httpMethod: POST
    version: 1
    editable: true

  - name: PostgreSQL
    type: postgres
    url: postgres-primary:5432
    database: tge_swarm
    user: swarm_user
    secureJsonData:
      password: swarm_secure_pass
    jsonData:
      sslmode: disable
      maxOpenConns: 10
      maxIdleConns: 2
      connMaxLifetime: 14400
    version: 1
    editable: true

  - name: Redis
    type: redis-datasource
    access: proxy
    url: redis://redis-master-1:7001
    secureJsonData:
      password: redis_secure_pass
    jsonData:
      client: standalone
      poolSize: 5
      timeout: 10
      pingInterval: 0
      pipelineWindow: 0
    version: 1
    editable: true